### ISSUE TITLE
Picture not showing

### ISSUE THREAD

**Issue by KuroXI** [Pizzabelly/EasyRP#114]
I upload the picture in dev site but when i reload the EZRP it won't show the big and small picture anyone can help me?

Also i suggest

Make it work in background and startup

**Comment by RealEzra** [comment]
Did you set the images equal to the name of the images you uploaded on discord?

**Comment by KuroXI** [comment]
I restart my pc and it works forgot I made a issue here

**Comment by RealEzra** [comment]
Do you want a way to make it auto start?

**Comment by LegitEzra** [comment]
@echo off
cls
ping -n 5 127.0.0.1 >nul
cd C:\Users\pathToEasyRP
start easyrp.exe

Open notepad and paste that then save as something.bat open task scheduler and click create basic task name it whatever you want then click next. Now make the trigger "When I Log on" make the action start a program finally click browse and select the something.bat file then finish the task. Now when you log on the batch file will open wait five seconds then it will open easyrp.exe. 
You can also try selecting the exe in the task scheduler but when i tried this easyrp gave me a config not found error so i made a batch file with a 5 sec delay.
