### ISSUE TITLE
Doesn't Seem To Still Work

### ISSUE THREAD

**Issue by KeplerIO** [Pizzabelly/EasyRP#116]
Title.

**Comment by M1nxy** [comment]
it does tho

**Comment by DylanD16** [comment]
Make sure you don't have a custom status set

**Comment by develop331** [comment]
Make sure that you have the Microsoft C++ tools installed (it might be windows, I have forgotten), your game presence on (inside the discord client), no custom status set, and config.ini setup correctly. Also, unzip the folder it comes in.
I hope that answers your question!

**Comment by BadMaliciousPyScripts** [comment]
> Make sure that you have the Microsoft C++ tools installed (it might be windows, I have forgotten), your game presence on (inside the discord client), no custom status set, and config.ini setup correctly. Also, unzip the folder it comes in.
> I hope that answers your question!

Thanks this actually helped me, after installing the Microsoft Visual Studio Build tools for 2019 everything worked perfectly! Download the Microsoft VS Build tools [here](https://visualstudio.microsoft.com/en/downloads/) or directly the installer from [here](https://visualstudio.microsoft.com/en/thank-you-downloading-visual-studio/?sku=BuildTools).
