### ISSUE TITLE
add start with windows option

### ISSUE THREAD

**Issue by UltimateWishub** [Pizzabelly/EasyRP#119]

**Comment by M1nxy** [comment]
yo there's an easy way to do this:
1) Open 2 windows of file explorer.

2) In One window navigate to where your easyrp.exe is stored.

3) In Window 2's address bar paste the following:
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp

4) Then in window 1 create a shortcut to easyrp.exe

5) Finally drop the new shortcut into window 2

6) It Should Now Auto Start On All Accounts

7) (OPTIONAL) If You Only Want It to Start For Your Windows Account replace Step 3 With Step 8

8) In Window 2's address paste the following (Replace [Username] with your username eg ..Users\Simon\Appdata..):
C:\Users\[User Name]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by M1nxy** [comment]
Hope This Helped :)

**Comment by UltimateWishub** [comment]
thx
