### ISSUE TITLE
Marked as virus by Norton

### ISSUE THREAD

**Issue by AntsyBoi** [Pizzabelly/EasyRP#137]
[image](https://user-images.githubusercontent.com/38162305/99414759-c2143900-28bc-11eb-9772-170dc42a398e.png)

**Comment by bhavyagosai** [comment]
Its an unrecognized EXE file so it would show as a threat...just like when one downloads crack files which are classified as a malware. I suggest you exclude it from scanning. It isnt a virus.

**Comment by AntsyBoi** [comment]
Oh ok
