### ISSUE TITLE
How do I run EasyRP in the background?

### ISSUE THREAD

**Issue by SeveralP** [Pizzabelly/EasyRP#147]
![image](https://user-images.githubusercontent.com/66889083/102698288-3dde0a00-420a-11eb-8907-ffb00f5a3683.png)

I don't want it to run like that want it to be one of the background tasks any idea how I would do that?

**Comment by bhavyagosai** [comment]
Check out this [Repo](https://github.com/bBSempai/EasyRP) 
Or this [PR](https://github.com/Pizzabelly/EasyRP/pull/138)

**Comment by develop331** [comment]
On Windows, you can create a new screen:
![image](https://user-images.githubusercontent.com/64089164/102715365-e785cf80-42cc-11eb-982b-829f3ffbb493.png)
Create a new screen by pressing this button, then the tab won't be visible but will still run

**Comment by SeveralP** [comment]
> On Windows, you can create a new screen:
> ![image](https://user-images.githubusercontent.com/64089164/102715365-e785cf80-42cc-11eb-982b-829f3ffbb493.png)
> Create a new screen by pressing this button, then the tab won't be visible but will still run

thanks
