### ISSUE TITLE
2 Features request :)

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Pizzabelly/EasyRP#15]
1- add elapsed time
2- add this thing to make the bot can work with "ASK TO JOIN" & "SPECTATE" buttons (i mean like this: https://discordapp.com/developers/docs/rich-presence/getting-approved )

**Comment by MrUnknownDE** [comment]
The second function request is not possible because you have to send a script to Discord, so the discord then lets you pass this app as a functionary and then you might get the function ...

Best regards
MrUnknownDE

**Comment by EsmailELBoBDev2** [comment]
ok, add elapsed time

**Comment by GeorgeCY2** [comment]
dk if that's possible, due to the creator stopped continuing the project looks like

**Comment by GeorgeCY2** [comment]
nvm it, now i saw the commits but maybe and maybe bot as in the previous one

**Comment by EsmailELBoBDev2** [comment]
RIP

**Comment by bonkmaykr** [comment]
@GeorgeCY2 he did
