### ISSUE TITLE
[SUGESTION] Option in config to run program without console window

### ISSUE THREAD

**Issue by Wolfyxon** [Pizzabelly/EasyRP#162]
Hi.
I'm using EasyRP to make DiscordRPC for my game, but players can be a little confused when a console window pops up.

**Comment by ASOwnerYT** [comment]
Yea, it would be great to be able to hide the console window, not just for games but for normal users like me who don't want the console window icon taking up their taskbar.

**Comment by PreciousWarrior** [comment]
For now, you can just move the console window to another virtual desktop to fix the problem temporarily

**Comment by Wolfyxon** [comment]
I think I can close this issue now since it's very old and there are much better ways such as using the official Discord's SDK.
(I apologize for my terrible English, I edited the first message)
