### ISSUE TITLE
[LINUX] unable to excute easyrp

### ISSUE THREAD

**Issue by darkRaspberry** [Pizzabelly/EasyRP#175]
## what's the issue.
Unable to run easyrp in linux

## expected
Run smoothly and show the output in terminal

## actual
after running from command line.
```
dev@xxxx:~/EasyRP-v3.0-linux$ ls
config.ini  easyrp  readme.txt
dev@xxxx:~/EasyRP-v3.0-linux$ ./easyrp
bash: ./easyrp: No such file or directory
```
Running at gui
![easyrp](https://user-images.githubusercontent.com/56693429/116859272-59780900-ac1d-11eb-87af-6fdc4d3233c9.png)

## other info
os: Linux - Ubuntu 21.04

**Comment by TECHNOFAB11** [comment]
Same issue, i just built it myself and that worked

**Comment by darkRaspberry** [comment]
I like to build this app. But i have history of meson never correctly build it. Anyway I will give it a try.

No i can't build it. It's so so so buggy the meson thing

**Comment by darkRaspberry** [comment]
FInally i got how its build. Thankssss

**Comment by soshimee** [comment]
I can't build, can you tell me? It keeps making PIE errors.

**Comment by darkRaspberry** [comment]
@soshimee PIE errors means?
Which os are u talking about

**Comment by soshimee** [comment]
```
[1/1] Linking target easyrp.
FAILED: easyrp 
c++  -o easyrp 'easyrp@exe/main.cpp.o' 'easyrp@exe/config.cpp.o' 'easyrp@exe/discord.cpp.o' -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group /home/soshimee/EasyRP/libdiscord-rpc.a -Wl,--end-group
/usr/bin/ld: /home/soshimee/EasyRP/libdiscord-rpc.a(discord_rpc.cpp.o): relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/soshimee/EasyRP/libdiscord-rpc.a(rpc_connection.cpp.o): relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/soshimee/EasyRP/libdiscord-rpc.a(serialization.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/soshimee/EasyRP/libdiscord-rpc.a(connection_unix.cpp.o): relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: /home/soshimee/EasyRP/libdiscord-rpc.a(discord_register_linux.cpp.o): relocation R_X86_64_32S against symbol `stderr@@GLIBC_2.2.5' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by soshimee** [comment]
I'm on Ubuntu 20.04

**Comment by darkRaspberry** [comment]
@soshimee There are two things to do one you have to build discord-rpc lib. Then using that lib you Have to build that file.
[earyrp-zip.zip](https://github.com/Pizzabelly/EasyRP/files/6723471/earyrp-zip.zip)
Take this zip file do neccessary modification in config and try to run.
I'm in 21.04 probably have enough capability. 

ALSO need replying? Pls metion

**Comment by Tubz786** [comment]
@darkRaspberry do you mind extending on how to build this? Do i clone this repo into my pi then do it or is there another process, because im thoroughly lost

**Comment by darkRaspberry** [comment]
If you want to run the app in pi, then clone in pi and run build instructions there.
