### ISSUE TITLE
Building on Linux and making images work

### ISSUE THREAD

**Issue by XShrimp** [Pizzabelly/EasyRP#183]
I've been trying to figure this out for a whole day, browsing the open/closed issues on this repo but couldn't find much help.
Using the Linux EasyRP tar.gz didn't work so I had to build it myself. So I'm leaving this here in hopes of helping someone figure it out.

Follow the build instructions in the **README.md** until the `make` part.
From the root folder, go to `discord-rpc/build/src` and move `libdiscord-rpc.a` to the root folder of your EasyRP then build it.
You'll have easyrp in the `/build` folder. Move the `config.ini` into the build folder, customize it then on your terminal do:
`cd [ wherever your EasyRP folder is ]/build`
`./easyrp`

So how to make the images work?
This might not be an actual solution but it worked for me.
![image](https://user-images.githubusercontent.com/51189035/120875719-3d82d100-c5e8-11eb-8bcc-c39c61ddbf55.png)

On the **Details** part, having the line "_you're telling me shrimp"_ breaks the code so to fix this I just did this, adding another `'` and a new line.

![image](https://user-images.githubusercontent.com/51189035/120875764-8175d600-c5e8-11eb-857a-38b27ad659d0.png)

Which fixed the broken no image issue whenever I ran the presence.

I hope this helps someone. G'luck with your builds~ o/

**Comment by Tubz786** [comment]
@XShrimp Is it possible to get this to work with a discord bot? I pasted the bot client ID in, and it runs but I see no rich presence on Discord, I didn't add any pictures yet just a simple word in detail and state
