### ISSUE TITLE
i dont know how it works and discord doesent recognize it

### ISSUE THREAD

**Issue by VasinklingGR** [Pizzabelly/EasyRP#2]
the config.ini is wierd what do i do? the only thing i recognized is client id the others i dont know
also discord is not recognizing the rich presence
please help

**Comment by GlitchMasta47** [comment]
Follow the instructions step by step in the readme

This is not very hard to do

**Comment by OotinnyoO1** [comment]
Details are the details of the description of the rich presence,
State is the state you are in, example, on discord, set state to discord.

[Images]
LargeImage is the needed part, it says about the picture of your application.

Also, you do need to put it on your application integration, not YOUR client id.
