### ISSUE TITLE
Discord shows Path to .exe but not the RP

### ISSUE THREAD

**Issue by rmcproductions** [Pizzabelly/EasyRP#20]
![image](https://user-images.githubusercontent.com/40141421/41201371-e509f054-6cb6-11e8-99e4-3054d058c944.png)

And yes, i got the client id and everything else right. Do I need to wait a bit just to make sure it gets "approved" or sth like that?

**Comment by GeorgeCY2** [comment]
have you checked assets are right?

**Comment by rmcproductions** [comment]
Sorry. I waited a bit and now it works. Seems to be a problem with discord, not EasyRP.
