### ISSUE TITLE
Can't I use 2byte letter  in EasyRP?

### ISSUE THREAD

**Issue by warioji** [Pizzabelly/EasyRP#38]
I think it's text garbling now.

**Comment by Pizzabelly** [comment]
Make sure you save the config.ini in utf-8. If that doesn't work, paste the letter so i can test. Something like this works for me.
![screenshot_20180713_210106](https://user-images.githubusercontent.com/8285260/42719206-2849f31c-86e0-11e8-855e-e35715f60bb4.png)

**Comment by warioji** [comment]
OMG. My character set wasn't utf-8. I tried utf-8 and it's works correctly. Thanks for your advice.
