### ISSUE TITLE
Elapsed Time

### ISSUE THREAD

**Issue by JerryTheSlime16** [Pizzabelly/EasyRP#41]
I am currently trying to make it say how long I have been playing the EasyRP after the "Details=" it put "StartTimestamp=1531342252".  Can someone please help me where I went wrong?

**Comment by Finnasaurus** [comment]
epochtime only https://www.epochconverter.com/

**Comment by JerryTheSlime16** [comment]
I did use epoch time.

**Comment by MuhdNurHidayat** [comment]
Try to add EndTimestamp=0 ?
What it currently showing?

**Comment by hirowatch** [comment]
thanks <3
