### ISSUE TITLE
Missing msvcp140.dll / vcruntime140.dll (FIX)

### ISSUE THREAD

**Issue by Eric00x** [Pizzabelly/EasyRP#45]
It's the problem of **Visual C++ 2015 Redistributable dlls (probably missing or corrupted)**
### Download [**it by clicking this link**](https://www.microsoft.com/en-US/download/details.aspx?id=48145)
If error 0x80070666 occurs, **try downloanding english version of x86** (my pc is x64 and it worked for me)

**Comment by Pizzabelly** [comment]
Thanks for the heads up. i added this to the readme.
