### ISSUE TITLE
Two DLL files are "missing"

### ISSUE THREAD

**Issue by ray27890** [Pizzabelly/EasyRP#58]
I tried starting my rich presence and I was greeted by an error that I don't know how to fix:
"The code execution cannot proceed because MSVCP140.dll , VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem."

**Comment by ray27890** [comment]
(Reinstalling the program doesn't fix it.)

**Comment by Eric00x** [comment]
Can you read readme.md

**Comment by ray27890** [comment]
yes I can, EasyRP (Custom Discord Rich Presence) https://github.com/Pizzabelly/EasyRP
1. First you need to register a Rich Presence application with discord
     - Go here https://discordapp.com/developers/applications/me
     - Make a new application **The name of the app will be the main name for the rich presence**
     - Enable rich presence for your app and add some assets
2 Download the latest release of EasyRP from here https://github.com/Pizzabelly/EasyRP/releases 
3 Edit the config file with the information from your newly registered app
4 Run easyrp (it should open a cmd window)
    - It *should* report errors from your config file (if there are any)
5 Discord should show the game on your profile
	- if not, add the exe as a game on discord and the file path should change to your presence

You can edit the config any time while the program is running to change the presence (make sure to save the file)

**Comment by ray27890** [comment]
nothing there looks like it could link to the error.

**Comment by Eric00x** [comment]
Again, can you read what you need to set up?

**Comment by ray27890** [comment]
a rich presence, I have that.

**Comment by Eric00x** [comment]
> if you are on Windows you also need Visual C++ Redistributable

**Comment by ray27890** [comment]
I have c++

**Comment by Eric00x** [comment]
download, try x86 if you downloaded it earlier

**Comment by ray27890** [comment]
![image](https://user-images.githubusercontent.com/17932849/44053424-86b52790-9f37-11e8-8ecc-ba4012f8dd05.png)

**Comment by Eric00x** [comment]
what i said: download x86

**Comment by Eric00x** [comment]
or repair it

**Comment by ray27890** [comment]
Done.

**Comment by ray27890** [comment]
huh, works now, thanks!
