### ISSUE TITLE
I can`t run easyrp on linux

### ISSUE THREAD

**Issue by er2off** [Pizzabelly/EasyRP#80]

**Comment by VariableVixen** [comment]
What happens when you try? Can you compile it successfully? If not, what happens when you try to compile it? The dev can't do anything without information.

**Comment by er2off** [comment]
I download the latest release for Linux. Command ./easyrp do not working.

**Comment by VariableVixen** [comment]
What happens when you run the command? What output is displayed?

**Comment by MeetPing** [comment]
nothing it just opens the file
